services:
  prometheus:
    image: prom/prometheus:latest
    container_name: task-tracker-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: task-tracker-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"